@startuml "Container diagram as is"

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml


Person(user, "User", "Пользователь приложения Теплый дом")
System(devices, "Партнерские устройства", "Подключенные умные устройства", "Uses REST API, JSON data format")
ContainerDb(db, "Database", "PostgreSQL", "Stores user data and application state")
System_Boundary(c1, "[Container] API]") {
    Component(sensor, "Sensor component", "Go", "Получение данных от устройств и отправка команд управления")
}

Rel(user, sensor, "Пользуется системой")
Rel(sensor,devices,"Получения данных и отправка команд управления")
Rel(sensor,db,"Reads from and writes to")


@enduml